spring:
  application:
    name: campaign-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate 
    show-sql: true
  datasource:
    username: thedockeruser
    password: passwordAAAAAAAAAAAAAAa
server:
  port: 0 
