spring:
  application:
    name: campaign-service # Name in Eureka Dashboard and for config-server
  config:
    import: configserver:http://localhost:8888 # TODO: Set docker service name and parametrize this value
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  sql:
    init:
      mode: never # always enables data.sql, but never is required for Liquibase
  jpa:
    defer-datasource-initialization: false # true enables data.sql, but false is required for Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # create would override tables, validate won't
    show-sql: true
  datasource:
    # url: jdbc:postgresql://db:5432/thedockerdb
    username: thedockeruser
    password: passwordAAAAAAAAAAAAAAa
server:
  port: 0 # Random port
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true